[package]
name = "papoo-htcacheclean"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1", features = ["derive"] }
thiserror = "1.0"
nix = "0.15.0"
libc = "0.2"
crossbeam = "0.8"
rand = "0.8"
num_cpus = "1.13"

[profile.release]
lto = true
codegen-units = 1
